name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: linux-build
        # A file, directory or wildcard pattern that describes what to upload
        path: ./expression.out
